### ISSUE TITLE
Missing jpeg header files means Pillow can't be built from source

### ISSUE THREAD

**Issue by mdboom** [faster-cpython/tools#134]
I think libjpeg-devel needs to be installed on the benchmarking machine so Pillow can be installed from source (for CPython main).

Should be straightforward, but wanted to run this by @ericsnowcurrently before making this change...

```
2022-12-02 19:13:08,630:       Traceback (most recent call last):
2022-12-02 19:13:08,630:         File "<string>", line 2, in <module>
2022-12-02 19:13:08,630:         File "<pip-setuptools-caller>", line 34, in <module>
2022-12-02 19:13:08,630:         File "/tmp/pip-install-w6o18pmz/pillow_2f0e08bb521844a18a08dc74efcfa05c/setup.py", line 914, in <module>
2022-12-02 19:13:08,630:           raise RequiredDependencyException(msg)
2022-12-02 19:13:08,630:       RequiredDependencyException:
2022-12-02 19:13:08,630:
2022-12-02 19:13:08,630:       The headers or library files could not be found for jpeg,
2022-12-02 19:13:08,630:       a required dependency when compiling Pillow from source.
2022-12-02 19:13:08,631:
2022-12-02 19:13:08,631:       Please see the install instructions at:
2022-12-02 19:13:08,631:          https://pillow.readthedocs.io/en/latest/installation.html
```

**Comment by ericsnowcurrently** [comment]
sounds okay
