### ISSUE TITLE
KeyError: 'uploadargs'.  when trying to run a benchmark

### ISSUE THREAD

**Issue by iritkatriel** [faster-cpython/tools#73]
```
iritkatriel@pyperf-portal:~$ bench BENCH/jobs.py run-bench --benchmarks='-flaskblogging' --remote iritkatriel --branch gh-92228 latest

Traceback (most recent call last):

  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/home/benchmarking/faster_cpython-tools/PORTAL/jobs/__main__.py", line 1067, in <module>

    cmd, cmd_kwargs, cfgfile, user, verbosity, logfile, devmode = parse_args()

  File "/home/benchmarking/faster_cpython-tools/PORTAL/jobs/__main__.py", line 976, in parse_args

    handle_request_args(args, parser)

  File "/home/benchmarking/faster_cpython-tools/PORTAL/jobs/__main__.py", line 710, in handle_args

    uploadargs = ns.pop('uploadargs')

KeyError: 'uploadargs'
```

**Comment by ericsnowcurrently** [comment]
The problem is that the "run-bench" command mimics "add compile-bench" but doesn't add all corresponding options, even though `handle_args()` expects them.  See https://github.com/faster-cpython/tools/blob/main/PORTAL/jobs/__main__.py#L688.

@mdboom's fix works.  We should follow up with a more correct fix though.
